<a href="https://colab.research.google.com/github/juwoncozyboy/Machine_learning/blob/main/day02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
lil = [1,2,3,4,'a', 'b']
print(lil, type(lil))
print(lil[2], lil[4], type(lil[2]), type(lil[4]))

li2 = [1,3,5,7]
print(lil + li2)
print(li2 * 3)

[1, 2, 3, 4, 'a', 'b'] <class 'list'>
3 a <class 'int'> <class 'str'>
[1, 2, 3, 4, 'a', 'b', 1, 3, 5, 7]
[1, 3, 5, 7, 1, 3, 5, 7, 1, 3, 5, 7]


# 2) 넘파이 배열구조

In [66]:
import numpy as np

#넘파이 배열 만들 때 np.array([])
ar1 = np.array([1,2,3,4,'a','b'])
print(ar1, type(ar1))
print(type(ar1.dtype)) #<U21

['1' '2' '3' '4' 'a' 'b'] <class 'numpy.ndarray'>
<class 'numpy.dtype[str_]'>


In [67]:
#넘파이 연산
ar2 = np.array([[1,2], [3,4]])
ar3 = np.array([[1,2], [3,4]])
print(ar2)
print(ar3)
print(ar2 + ar3)
print(ar2 - ar3)
#정수형과 실수형 -> 실수형으로 통일
#숫자형과 문자열 -> <U23 문자열로 통일

ar4 = np.array([[1,2,3], [4,5]])
print(ar4, type(ar4)) # 리스트로 묶여서 출력되는 것 확인, 자료형은 numpy.daarray

print(np.__version__)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[list([1, 2, 3]) list([4, 5])] <class 'numpy.ndarray'>
1.22.4


<ipython-input-67-4fb098366622>:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar4 = np.array([[1,2,3], [4,5]])


2) 넘파이 객체의 속성

In [68]:
#1차원
arr1 = np.array([1.0, 20])
print(arr1, type(arr1))
print(arr1[0], type(arr1[0]))
print(arr1[1])
#데이터 타입 확인
print(arr1.dtype)

#2차원
arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)

#크기 shape
print(arr1.shape) #1행 2열
print(arr2.shape) #2행 3열

#차원 ndim
print(arr1.ndim)
print(arr2.ndim)

#크기 size
print(arr1.size)
print(arr2.size)

#데이터타입 dtype
print(arr1.dtype)
print(arr2.dtype)

[ 1. 20.] <class 'numpy.ndarray'>
1.0 <class 'numpy.float64'>
20.0
float64
[[1 2 3]
 [4 5 6]]
(2,)
(2, 3)
1
2
2
6
float64
int64


### 3 넘파이 함수

In [69]:
#넘파이 검색, 수정, 추가, 삭제
#검색
#1차원
print(arr1)
print(arr1[1])

#2차원
print(arr2) #2행 3열
print(arr2[0][1]) #0행 1열에 있는 데이터 출력
print(arr2[0]) #0행 출력

[ 1. 20.]
20.0
[[1 2 3]
 [4 5 6]]
2
[1 2 3]


In [70]:
#수정
#리스트
li1 = [1, 2, 3]
print(li1)
li1[0] = 10
print(li1)

#넘파이 수정
print(arr1)
print(arr2)
arr1[0] = 10 #기존에 있는 값이 변경된 값으로 변수에 재할당됨
print(arr1)

#2차원
arr2[0][2] = 100
print(arr2)

[1, 2, 3]
[10, 2, 3]
[ 1. 20.]
[[1 2 3]
 [4 5 6]]
[10. 20.]
[[  1   2 100]
 [  4   5   6]]


In [71]:
#추가
#np.append(배열1, 배열2, 축)
arr3 = np.array([[1,2], [3,4]])
print(arr3)
print(arr3.ndim)

#행을 추가
arr3 = np.append(arr3, [[1,1]], axis=0)
print(arr3)

arr4 = np.append(arr3, [[1,1],[2,2],[3,3]], axis = 1)
#axis = 1 열이 추가
print(arr4)

[[1 2]
 [3 4]]
2
[[1 2]
 [3 4]
 [1 1]]
[[1 2 1 1]
 [3 4 2 2]
 [1 1 3 3]]


In [72]:
#삭제
#np.delete(배열, 인덱스, 축)
#2차원 > axis 0행 axis 1열
#3차원 > axis 0 높이, axis 1 행, axis 2 열

print(arr4)
print(np.delete(arr4, 1, axis = 0)) #단순 1회성 삭제
print(arr4)

[[1 2 1 1]
 [3 4 2 2]
 [1 1 3 3]]
[[1 2 1 1]
 [1 1 3 3]]
[[1 2 1 1]
 [3 4 2 2]
 [1 1 3 3]]


In [73]:
arr5 = np.array([[1, 2], [3, 4]])
arr6 = np.array([[5, 6], [7, 8]])
print(np.append(arr5, arr6))
print(np.append(arr5, arr6, axis = 0)) #4행 2열
print(np.append(arr5, arr6, axis = 1)) #2행 4열

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [74]:
#np.zeros() 모든 값이 0으로만 이루어진 배열만들기
#자료형을 기재하지 않으면 실수형으로 만들어짐

z1 = np.zeros((2, 5))
print(z1, z1.dtype)

#int 정수형
z2 = np.zeros((2, 5), dtype = 'i')
print(z2, z2.dtype)

#unit형
z3 = np.zeros((2, 5), dtype = 'I')
print(z3, z3.dtype)

#유니코드
z4 = np.zeros((2, 5), dtype = 'U')
print(z4, z4.dtype)

#bool
z5 = np.zeros((2, 5), dtype = '?')
print(z5, z5.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] float64
[[0 0 0 0 0]
 [0 0 0 0 0]] int32
[[0 0 0 0 0]
 [0 0 0 0 0]] uint32
[['' '' '' '' '']
 ['' '' '' '' '']] <U1
[[False False False False False]
 [False False False False False]] bool


In [75]:
#np.ones() 모든 값이 1로 이루어진 배열 만들기
o1 = np.ones((2, 5))
print(o1, o1.dtype)

o2 = np.ones((2, 5), dtype = 'i')
print(o2, o2.dtype)

o3 = np.ones((2, 5), dtype = '?')
print(o3, o3.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float64
[[1 1 1 1 1]
 [1 1 1 1 1]] int32
[[ True  True  True  True  True]
 [ True  True  True  True  True]] bool


In [76]:
#np.arange() 연속된 정수로 배열만들기(실수도 가능)
#arange(시작값, 종료값, 스텝값)

arr1 = np.arange(1, 10, 2)
print(arr1, arr1.dtype)

arr2 = np.arange(1, 10, 2, dtype = 'f')
print(arr2, arr2.dtype)

arr3 = np.arange(1, 10, 2.5)    #np의 arange()함수는 실수형 가능
print(arr3, arr3.dtype)

# li1 = list(range(1, 10, 2.5)) #range()함수는 실수형 불가
# print(li1, type(li1))

[1 3 5 7 9] int64
[1. 3. 5. 7. 9.] float32
[1.  3.5 6.  8.5] float64


In [77]:
#transpose()
#2행 3열 np 배열 만들기 1, 2,3 4,5,6
t1 = np.array([[1, 2, 3], [4, 5, 6]])
print(t1, t1.dtype)

#0행 1열의 값
print(t1[0][1])
print(t1[1][0])

#3행 2열로 바꾸기
t2 = t1.transpose()
print(t2)

t3 = t2.T
print(t3)

[[1 2 3]
 [4 5 6]] int64
2
4
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [78]:
#2행 2열
#ar1 = 10, 20] 30 40
#ar2 = 1, 2] [3, 4]

#dtype, ndim, shape, size
# + - * /

ar1 = np.array([[10, 20], [30, 40]])
ar2 = np.array([[1, 2] ,[3, 4]])

print(ar1.dtype)
print(ar2.dtype)
print(ar1.ndim)
print(ar2.ndim)
print(ar1.shape)
print(ar2.shape)
print(ar1.size)
print(ar2.size)

print(f"ar1 + ar2 = ")


int64
int64
2
2
(2, 2)
(2, 2)
4
4
ar1 + ar2 = 


In [79]:
#브로드캐스팅기능 : 크기가 서로 다른 배열끼리 사칙연산을 가능하게 함

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])
print(arr1 + arr2)

arr3 = np.array([5])
print(arr1.shape, arr3.shape)
print(arr1 + arr3) #행이 같고 열이 다름(계산가능)

arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.shape)
print(arr4.shape)
print(arr1 + arr4) #1차원과 2차원 행이 다르고 열이 같음(계산가능)
arr1 = np.array([1, 2, 3])

arr5 = np.array([[10], [20]])
print(arr5.shape)
print(arr5)
print(arr4, arr4.shape)
print(arr4 + arr5)

[4 6 8]
(3,) (1,)
[6 7 8]
(3,)
(2, 3)
[[2 4 6]
 [5 7 9]]
(2, 1)
[[10]
 [20]]
[[1 2 3]
 [4 5 6]] (2, 3)
[[11 12 13]
 [24 25 26]]


In [80]:
#[실습]
#arr1은 2차원 배열 크기 2,4
#arr2은 1차원 배열 크기 4

#요소별 덧셈과 곱셈 수행 후 출력
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.shape, arr1.ndim, arr1.dtype, arr1.size)
arr2 = np.array([2,4,6,8])
print(arr2.shape, arr2.ndim, arr2.dtype, arr2.size)

print(arr1 + arr2)
print(arr1 * arr2)


(2, 4) 2 int64 8
(4,) 1 int64 4
[[ 3  6  9 12]
 [ 7 10 13 16]]
[[ 2  8 18 32]
 [10 24 42 64]]


In [81]:
arr1 = np.array([[1, 2, 3]])
print(arr1, arr1.dtype, arr1.shape, arr1.ndim)
arr2 = np.array([4, 5, 6])
#arr1을 2차원 배열로 확장해서 크기를 (1, 3)만든 상태로
#arr1에 arr2를 추가하고(append 행에 추가)
#arr1 + arr2 결과출력

print(arr2, arr2.dtype, arr2.shape, arr2.ndim)
arr1 = np.append(arr1, [arr2], axis = 0)
print(arr1)
print(arr1 + arr2)

[[1 2 3]] int64 (1, 3) 2
[4 5 6] int64 (3,) 1
[[1 2 3]
 [4 5 6]]
[[ 5  7  9]
 [ 8 10 12]]


#5. 시리즈(Series)


In [82]:
import pandas as pd
s = pd.Series(['AI', 2023, 7, 16], index = ['a', 'b', 'c', 'd'],
              name = 'test')
print(s)

a      AI
b    2023
c       7
d      16
Name: test, dtype: object


2) 딕셔너리 -> 시리즈 변환

In [83]:
student = {'math': 90, 'english': 90, 'korean': 100, 'his':88}
print(student, type(student))
print(student.values())
print(student.keys())
print(student.items())

#딕셔너리 -> 시리즈 변환
s_student = pd.Series(student, name = "scoer")
print(s_student)

s_student = pd.Series(student, index = ['a', 'b', 'c', 'd'])
print(s_student)

{'math': 90, 'english': 90, 'korean': 100, 'his': 88} <class 'dict'>
dict_values([90, 90, 100, 88])
dict_keys(['math', 'english', 'korean', 'his'])
dict_items([('math', 90), ('english', 90), ('korean', 100), ('his', 88)])
math        90
english     90
korean     100
his         88
Name: scoer, dtype: int64
a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64


##3) 리스트, 튜플 -> 시리즈로 변환

In [84]:
num = [1, 2, 3, 4, 5]
s_num = pd.Series(num, index = ['one', 'two', 'three', 'four', 'five'])
print(s_num)

#인덱스만 출력
print(s_num.index)
#값만 출력
print(s_num.values)
#타입
print(s_num.dtype)

one      1
two      2
three    3
four     4
five     5
dtype: int64
Index(['one', 'two', 'three', 'four', 'five'], dtype='object')
[1 2 3 4 5]
int64


In [85]:
data = 'python', '20230716', True
print(data, type(data))

s_data = pd.Series(data, index = ['과목', '날짜', '강의수강여부'])
print(s_data)

#원소 선택(2가지 방법)
#방법1 : 정수형 위치 인덱스를 사용 => 리스트와 같은 원리
print(s_data[0])

#방법2 : 인덱스 이름(라벨)를 사용 -> 딕셔너리와 같은 원리
print(s_data['과목'])

#여러값을 인덱싱
print(s_data[[1,2]]) #인덱스를 이용할 때는 대괄호 2개 사용
#인덱스 리스트 [1,2]를 사용해서 해당 정수 인덱스에 해당하는 값을 선택

print(s_data[1:]) #슬라이싱으로 인덱싱 할 때는 대괄호를 하나만 사용

print(s_data[['날짜', '강의수강여부']])
# 레이블인덱스 리스트 ['날짜' , '강의수강여부']를 사용해서
# 해당하는 레이블 인덱스에 해당하는 값들을 선택

('python', '20230716', True) <class 'tuple'>
과목          python
날짜        20230716
강의수강여부        True
dtype: object
python
python
날짜        20230716
강의수강여부        True
dtype: object
날짜        20230716
강의수강여부        True
dtype: object
날짜        20230716
강의수강여부        True
dtype: object


##4) 시리즈-> 딕셔너리 또는 리스트 변환

In [87]:
s_student = pd.Series(student, name = "score")
print(s_student)

#시리즈 -> 리스트 변환 시 list() 형변환 이용
li = list(s_student)
print(li)

#시리즈 -> 딕셔너리 변환시 dict() 형변환
print(s_num)
di = dict(s_num)
print(di)

math        90
english     90
korean     100
his         88
Name: score, dtype: int64
[90, 90, 100, 88]
one      1
two      2
three    3
four     4
five     5
dtype: int64
{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}


##5) 시리즈 값 수정, 추가, 삭제

In [89]:
#시리즈 이름 부여(변경)
print(s_student)

s_student.name = '성적'
print(s_student)

#시리즈 인덱스 수정
s_student.rename({'english':'eng'})
#inplace 속성값을 주지 않으면 원본에 영향을 미치지 않음
print(s_student)

s_student.rename({'english':'eng'}, inplace = True)
print(s_student)

s_student.rename({'korean' : 'kor'})
print(s_student)

math       90
eng        90
korean    100
his        88
Name: 성적, dtype: int64
math       90
eng        90
korean    100
his        88
Name: 성적, dtype: int64
math       90
eng        90
korean    100
his        88
Name: 성적, dtype: int64
math       90
eng        90
korean    100
his        88
Name: 성적, dtype: int64
math       90
eng        90
korean    100
his        88
Name: 성적, dtype: int64


In [94]:
#시리즈값 찾기
print(s_student)
print(s_student['math'])
print(s_student[0])

math       90
eng        90
korean    100
his        88
Name: 성적, dtype: int64
90
90


In [101]:
#값 수정
#key(인덱스 레이블) 사용하여 특정 값 수정하기
s = pd.Series([10, 20, 30, 40, 50], index = ['A', 'B', 'C', 'D', 'E'])
print(s)

s['B'] = 25
print(s)

#인덱스(위치)를 사용하여 값 변경
s[1] = 20
print(s)

#인덱스이름 수정
s.rename(index = {'A':'Apple', 'B':'Banana', 'C':'Cerry'}, inplace = True)
print(s)

new_index = ['A', 'B', 'C', 'd', 'e']
s.set_axis(new_index, inplace=True)
print(s)


A    10
B    20
C    30
D    40
E    50
dtype: int64
A    10
B    25
C    30
D    40
E    50
dtype: int64
A    10
B    20
C    30
D    40
E    50
dtype: int64
Apple     10
Banana    20
Cerry     30
D         40
E         50
dtype: int64
A    10
B    20
C    30
d    40
e    50
dtype: int64


<ipython-input-101-1b6d1b8f3e95>:18: FutureWarning: Series.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  s.set_axis(new_index, inplace=True)


In [115]:
di_data = {'서울':1, '경기':2, '강원':3}
li_data = [2023, 07.16, 'AI', 100, True]

s1 = pd.Series(di_data)
s2 = pd.Series(li_data)
print(s1)
print(s2)

#1. s1, s2의 인덱스변경 rename 이용
# s1 => 'A', 'B', 'C'
# s2 => 'x', 'y', 'z', 'w', 'v'
s1.rename(index={'서울':'A'}, inplace = True)
s2.rename(index={0:'x'}, inplace = True)
print(s1)
print(s2)

#2. s1의 값변경 A의 값 10
#   s2의 값 변경 2023 2024
s1['A'] = 10
s2['x'] = 2024
print(s1)
print(s2)


# +) rename이용하지 않고 인덱스 변경(.index 이용)
# s1 => a, b, c,
s1.index = ['a', 'b', 'c']
print(s1)
# s2 => X, Y, Z, I, J
s2.index = ['X', 'Y', 'Z', 'I', 'J']
print(s2)

서울    1
경기    2
강원    3
dtype: int64
0    2023
1    7.16
2      AI
3     100
4    True
dtype: object
A     1
경기    2
강원    3
dtype: int64
x    2023
1    7.16
2      AI
3     100
4    True
dtype: object
A     10
경기     2
강원     3
dtype: int64
x    2024
1    7.16
2      AI
3     100
4    True
dtype: object
a    10
b     2
c     3
dtype: int64
X    2024
Y    7.16
Z      AI
I     100
J    True
dtype: object


In [120]:
#값 추가
#방법1) append()
s1 = s1.append(pd.Series({'인천' : 5}))
print(s1)
s2 = s2.append(pd.Series([2000, 2001]))
print(s2)
#방법2) 인덱스를 확장해서 값 추가

print(s2)

s1['d'] = 4
print(s1)
s2['A'] = 5.11
print(s2)

a     10
b      2
c      3
d      4
인천     5
인천     5
dtype: int64
X    2024
Y    7.16
Z      AI
I     100
J    True
A    5.11
0    2000
1    2001
dtype: object
X    2024
Y    7.16
Z      AI
I     100
J    True
A    5.11
0    2000
1    2001
dtype: object
a     10
b      2
c      3
d      4
인천     5
인천     5
dtype: int64
X    2024
Y    7.16
Z      AI
I     100
J    True
A    5.11
0    2000
1    2001
dtype: object


<ipython-input-120-77dd497ed364>:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s1 = s1.append(pd.Series({'인천' : 5}))
<ipython-input-120-77dd497ed364>:5: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s2 = s2.append(pd.Series([2000, 2001]))


In [133]:
#삭제
print(s1)
print(s2)

#1) drop 이용
# s1 = s1.drop('인천')
# print(s1)
# s2 = s2.drop(0)
# print(s2)

#2) del 키워드 이용
# del s1['a']
# print(s1)

# del s2['A']
print(s2)

#3) pop 이용
s2.pop('I')
print(s2)

X    2024
Y    7.16
Z      AI
J    True
0    2000
1    2001
dtype: object
